import type { Company, Contact, Relationship } from './api/types';

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'TechCorp Solutions',
    type: 'CUSTOMER',
    taxNumber: 'TC001234567',
    email: 'info@techcorp.com',
    phone: '+381112223344',
    address: 'Knez Mihailova 12',
    city: 'Belgrade',
    country: 'RS',
    postalCode: '11000',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '2',
    name: 'Global Imports LLC',
    type: 'SUPPLIER',
    taxNumber: 'GI002345678',
    email: 'contact@globalimports.com',
    phone: '+381211234567',
    address: 'Bulevar Oslobođenja 45',
    city: 'Novi Sad',
    country: 'RS',
    postalCode: '21000',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '3',
    name: 'Innovation Partners',
    type: 'PARTNER',
    taxNumber: 'IP003456789',
    email: 'hello@innovationpartners.com',
    phone: '+381182223344',
    address: 'Trg Kralja Milana 8',
    city: 'Niš',
    country: 'RS',
    postalCode: '18000',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '4',
    name: 'Retail Masters Inc',
    type: 'CUSTOMER',
    taxNumber: 'RM004567890',
    email: 'info@retailmasters.com',
    phone: '+381341234567',
    address: 'Svetozara Markovića 23',
    city: 'Kragujevac',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '5',
    name: 'Manufacturing Plus',
    type: 'SUPPLIER',
    taxNumber: 'MP005678901',
    email: 'info@manufacturingplus.com',
    phone: '+381241234567',
    address: 'Korzo 15',
    city: 'Subotica',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '6',
    name: 'Digital Solutions Group',
    type: 'CUSTOMER',
    taxNumber: 'DS006789012',
    email: 'info@digitalsolutions.com',
    phone: '+38512345678',
    address: 'Ilica 242',
    city: 'Zagreb',
    country: 'HR',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '7',
    name: 'Supply Chain Experts',
    type: 'SUPPLIER',
    taxNumber: 'SC007890123',
    email: 'info@supplychainexperts.com',
    phone: '+38612345678',
    address: 'Čopova ulica 5',
    city: 'Ljubljana',
    country: 'SI',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '8',
    name: 'Strategic Ventures',
    type: 'PARTNER',
    taxNumber: 'SV008901234',
    email: 'info@strategicventures.com',
    phone: '+38733123456',
    address: 'Ferhadija 12',
    city: 'Sarajevo',
    country: 'BA',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '9',
    name: 'Enterprise Systems Ltd',
    type: 'CUSTOMER',
    taxNumber: 'ES009012345',
    email: 'info@enterprisesystems.com',
    phone: '+38220123456',
    address: 'Slobode 34',
    city: 'Podgorica',
    country: 'ME',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '10',
    name: 'Logistics Pro',
    type: 'SUPPLIER',
    taxNumber: 'LP010123456',
    email: 'info@logisticspro.com',
    phone: '+38923123456',
    address: 'Macedonia 67',
    city: 'Skopje',
    country: 'MK',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '11',
    name: 'Business Partners Co',
    type: 'PARTNER',
    taxNumber: 'BP011234567',
    email: 'info@businesspartners.com',
    phone: '+381113334455',
    address: 'Terazije 25',
    city: 'Belgrade',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '12',
    name: 'Cloud Services Inc',
    type: 'CUSTOMER',
    taxNumber: 'CS012345678',
    email: 'info@cloudservices.com',
    phone: '+381214445566',
    address: 'Zmaj Jovina 10',
    city: 'Novi Sad',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '13',
    name: 'Hardware Supplies',
    type: 'SUPPLIER',
    taxNumber: 'HS013456789',
    email: 'info@hardwaresupplies.com',
    phone: '+381185556677',
    address: 'Obrenovićeva 18',
    city: 'Niš',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '14',
    name: 'Consulting Group',
    type: 'PARTNER',
    taxNumber: 'CG014567890',
    email: 'info@consultinggroup.com',
    phone: '+381116667788',
    address: 'Kralja Petra 45',
    city: 'Belgrade',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '15',
    name: 'Retail Chain',
    type: 'CUSTOMER',
    taxNumber: 'RC015678901',
    email: 'info@retailchain.com',
    phone: '+381347778899',
    address: 'Glavni trg 3',
    city: 'Kragujevac',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '16',
    name: 'Import Export Co',
    type: 'SUPPLIER',
    taxNumber: 'IE016789012',
    email: 'info@importexport.com',
    phone: '+38518889900',
    address: 'Zrinjevac 8',
    city: 'Zagreb',
    country: 'HR',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '17',
    name: 'Tech Innovations',
    type: 'CUSTOMER',
    taxNumber: 'TI017890123',
    email: 'info@techinnovations.com',
    phone: '+38619991122',
    address: 'Kongresni trg 12',
    city: 'Ljubljana',
    country: 'SI',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '18',
    name: 'Distribution Network',
    type: 'SUPPLIER',
    taxNumber: 'DN018901234',
    email: 'info@distributionnetwork.com',
    phone: '+381112223355',
    address: 'Makedonska 22',
    city: 'Belgrade',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '19',
    name: 'Financial Partners',
    type: 'PARTNER',
    taxNumber: 'FP019012345',
    email: 'info@financialpartners.com',
    phone: '+381214445577',
    address: 'Trg Slobode 7',
    city: 'Novi Sad',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '20',
    name: 'E-Commerce Solutions',
    type: 'CUSTOMER',
    taxNumber: 'EC020123456',
    email: 'info@ecommercesolutions.com',
    phone: '+381185556688',
    address: 'Vozda Karađorđa 55',
    city: 'Niš',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '21',
    name: 'Manufacturing Solutions',
    type: 'SUPPLIER',
    taxNumber: 'MS021234567',
    email: 'info@manufacturingsolutions.com',
    phone: '+381246667799',
    address: 'Matije Korvina 8',
    city: 'Subotica',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '22',
    name: 'Marketing Agency Pro',
    type: 'PARTNER',
    taxNumber: 'MA022345678',
    email: 'info@marketingagency.com',
    phone: '+381117778800',
    address: 'Strahinjića Bana 12',
    city: 'Belgrade',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '23',
    name: 'Software Development Inc',
    type: 'CUSTOMER',
    taxNumber: 'SD023456789',
    email: 'info@softwaredevelopment.com',
    phone: '+38518889911',
    address: 'Preradovićeva 15',
    city: 'Zagreb',
    country: 'HR',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '24',
    name: 'Construction Materials',
    type: 'SUPPLIER',
    taxNumber: 'CM024567890',
    email: 'info@constructionmaterials.com',
    phone: '+38619990022',
    address: 'Slovenska cesta 20',
    city: 'Ljubljana',
    country: 'SI',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
  {
    id: '25',
    name: 'International Trading',
    type: 'PARTNER',
    taxNumber: 'IT025678901',
    email: 'info@internationaltrading.com',
    phone: '+381111112233',
    address: 'Nemanjina 4',
    city: 'Belgrade',
    country: 'RS',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    contacts: [],
  },
];

export const mockContacts: Contact[] = [
  {
    id: 'c1',
    companyId: '1',
    firstName: 'Marko',
    lastName: 'Petrović',
    email: 'marko.petrovic@techcorp.com',
    phone: '+381601234567',
    position: 'CEO',
    department: 'Executive',
    tags: ['vip', 'decision_maker'],
    isPrimary: true,
    notes: 'Primary contact for TechCorp Solutions',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c2',
    companyId: '2',
    firstName: 'Ana',
    lastName: 'Jovanović',
    email: 'ana.jovanovic@globalimports.com',
    phone: '+381602345678',
    position: 'Sales Manager',
    department: 'Sales',
    tags: ['sales'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c3',
    companyId: '3',
    firstName: 'Nikola',
    lastName: 'Nikolić',
    email: 'nikola.nikolic@innovationpartners.com',
    phone: '+381603456789',
    position: 'CTO',
    department: 'IT',
    tags: ['technical', 'senior'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c4',
    companyId: '4',
    firstName: 'Jelena',
    lastName: 'Đorđević',
    email: 'jelena.djordjevic@retailmasters.com',
    phone: '+381604567890',
    position: 'Marketing Director',
    department: 'Marketing',
    tags: ['marketing'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c5',
    companyId: '5',
    firstName: 'Stefan',
    lastName: 'Ilić',
    email: 'stefan.ilic@manufacturingplus.com',
    phone: '+381605678901',
    position: 'Operations Manager',
    department: 'Operations',
    tags: ['operations'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c6',
    companyId: '6',
    firstName: 'Milica',
    lastName: 'Marković',
    email: 'milica.markovic@digitalsolutions.com',
    phone: '+381606789012',
    position: 'Product Manager',
    department: 'Product',
    tags: ['product'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c7',
    companyId: '7',
    firstName: 'Aleksandar',
    lastName: 'Stanković',
    email: 'aleksandar.stankovic@supplychainexperts.com',
    phone: '+381607890123',
    position: 'CFO',
    department: 'Finance',
    tags: ['finance', 'senior'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c8',
    companyId: '8',
    firstName: 'Jovana',
    lastName: 'Pavlović',
    email: 'jovana.pavlovic@strategicventures.com',
    phone: '+381608901234',
    position: 'HR Manager',
    department: 'Human Resources',
    tags: ['hr'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c9',
    companyId: '9',
    firstName: 'Đorđe',
    lastName: 'Simić',
    email: 'djordje.simic@enterprisesystems.com',
    phone: '+381609012345',
    position: 'CEO',
    department: 'Executive',
    tags: ['vip', 'decision_maker'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c10',
    companyId: '10',
    firstName: 'Tamara',
    lastName: 'Kovačević',
    email: 'tamara.kovacevic@logisticspro.com',
    phone: '+381610123456',
    position: 'Sales Manager',
    department: 'Sales',
    tags: ['sales'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c11',
    companyId: '11',
    firstName: 'Ivan',
    lastName: 'Petrović',
    email: 'ivan.petrovic@businesspartners.com',
    phone: '+381611234567',
    position: 'CTO',
    department: 'IT',
    tags: ['technical'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c12',
    companyId: '12',
    firstName: 'Sanja',
    lastName: 'Jovanović',
    email: 'sanja.jovanovic@cloudservices.com',
    phone: '+381612345678',
    position: 'Marketing Director',
    department: 'Marketing',
    tags: ['marketing', 'senior'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c13',
    companyId: '13',
    firstName: 'Marko',
    lastName: 'Nikolić',
    email: 'marko.nikolic@hardwaresupplies.com',
    phone: '+381613456789',
    position: 'Operations Manager',
    department: 'Operations',
    tags: ['operations'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c14',
    companyId: '14',
    firstName: 'Ana',
    lastName: 'Đorđević',
    email: 'ana.djordjevic@consultinggroup.com',
    phone: '+381614567890',
    position: 'CFO',
    department: 'Finance',
    tags: ['finance'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c15',
    companyId: '15',
    firstName: 'Nikola',
    lastName: 'Ilić',
    email: 'nikola.ilic@retailchain.com',
    phone: '+381615678901',
    position: 'Product Manager',
    department: 'Product',
    tags: ['product'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c16',
    companyId: '16',
    firstName: 'Jelena',
    lastName: 'Marković',
    email: 'jelena.markovic@importexport.com',
    phone: '+381616789012',
    position: 'HR Manager',
    department: 'Human Resources',
    tags: ['hr'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c17',
    companyId: '17',
    firstName: 'Stefan',
    lastName: 'Stanković',
    email: 'stefan.stankovic@techinnovations.com',
    phone: '+381617890123',
    position: 'CEO',
    department: 'Executive',
    tags: ['vip', 'decision_maker'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c18',
    companyId: '18',
    firstName: 'Milica',
    lastName: 'Pavlović',
    email: 'milica.pavlovic@distributionnetwork.com',
    phone: '+381618901234',
    position: 'Sales Manager',
    department: 'Sales',
    tags: ['sales'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c19',
    companyId: '19',
    firstName: 'Aleksandar',
    lastName: 'Simić',
    email: 'aleksandar.simic@financialpartners.com',
    phone: '+381619012345',
    position: 'CTO',
    department: 'IT',
    tags: ['technical', 'senior'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c20',
    companyId: '20',
    firstName: 'Jovana',
    lastName: 'Kovačević',
    email: 'jovana.kovacevic@ecommercesolutions.com',
    phone: '+381620123456',
    position: 'Marketing Director',
    department: 'Marketing',
    tags: ['marketing'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c21',
    companyId: '21',
    firstName: 'Đorđe',
    lastName: 'Petrović',
    email: 'djordje.petrovic@manufacturingsolutions.com',
    phone: '+381621234567',
    position: 'Operations Manager',
    department: 'Operations',
    tags: ['operations'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c22',
    companyId: '22',
    firstName: 'Tamara',
    lastName: 'Jovanović',
    email: 'tamara.jovanovic@marketingagency.com',
    phone: '+381622345678',
    position: 'CFO',
    department: 'Finance',
    tags: ['finance'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c23',
    companyId: '23',
    firstName: 'Ivan',
    lastName: 'Nikolić',
    email: 'ivan.nikolic@softwaredevelopment.com',
    phone: '+381623456789',
    position: 'Product Manager',
    department: 'Product',
    tags: ['product', 'senior'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'c24',
    companyId: '24',
    firstName: 'Sanja',
    lastName: 'Đorđević',
    email: 'sanja.djordjevic@constructionmaterials.com',
    phone: '+381624567890',
    position: 'HR Manager',
    department: 'Human Resources',
    tags: ['hr'],
    isPrimary: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockRelationships: Relationship[] = [
  {
    id: 'r1',
    sourceCompanyId: '1',
    targetCompanyId: '2',
    relationType: 'SUPPLIER',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceCompany: mockCompanies[0],
    targetCompany: mockCompanies[1],
  },
  {
    id: 'r2',
    sourceCompanyId: '3',
    targetCompanyId: '1',
    relationType: 'PARTNER',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceCompany: mockCompanies[2],
    targetCompany: mockCompanies[0],
  },
  {
    id: 'r3',
    sourceCompanyId: '4',
    targetCompanyId: '5',
    relationType: 'SUPPLIER',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceCompany: mockCompanies[3],
    targetCompany: mockCompanies[4],
  },
  {
    id: 'r4',
    sourceCompanyId: '6',
    targetCompanyId: '7',
    relationType: 'CUSTOMER',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceCompany: mockCompanies[5],
    targetCompany: mockCompanies[6],
  },
  {
    id: 'r5',
    sourceCompanyId: '8',
    targetCompanyId: '9',
    relationType: 'PARTNER',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceCompany: mockCompanies[7],
    targetCompany: mockCompanies[8],
  },
  {
    id: 'r6',
    sourceCompanyId: '10',
    targetCompanyId: '11',
    relationType: 'SUPPLIER',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceCompany: mockCompanies[9],
    targetCompany: mockCompanies[10],
  },
  {
    id: 'r7',
    sourceCompanyId: '12',
    targetCompanyId: '13',
    relationType: 'CUSTOMER',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceCompany: mockCompanies[11],
    targetCompany: mockCompanies[12],
  },
  {
    id: 'r8',
    sourceCompanyId: '14',
    targetCompanyId: '15',
    relationType: 'PARTNER',
    status: 'INACTIVE',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceCompany: mockCompanies[13],
    targetCompany: mockCompanies[14],
  },
  {
    id: 'r9',
    sourceCompanyId: '1',
    targetCompanyId: '16',
    relationType: 'SUPPLIER',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceCompany: mockCompanies[0],
    targetCompany: mockCompanies[15],
  },
  {
    id: 'r10',
    sourceCompanyId: '17',
    targetCompanyId: '18',
    relationType: 'CUSTOMER',
    status: 'ACTIVE',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceCompany: mockCompanies[16],
    targetCompany: mockCompanies[17],
  },
];

